import 'dart:async';
import 'dart:convert';

import 'package:chat_app/locker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:http/http.dart';
// ignore: unused_import
import 'package:local_auth/local_auth.dart';
import 'database_helper.dart';

StreamController _streamController;
Stream _stream;

Stream getList() async* {
  try {
    final dbHelper = CreateNotes.instance;
    final allRows = await dbHelper.queryAllRows();
    _streamController.add(allRows);
  } catch (e) {
    print(e);
  }
}

bool createnote = false;

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class Autogenerated {
  String q;
  String a;
  String h;

  Autogenerated({this.q, this.a, this.h});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    q = json['q'];
    a = json['a'];
    h = json['h'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['q'] = this.q;
    data['a'] = this.a;
    data['h'] = this.h;
    return data;
  }
}

class _HomePageState extends State<HomePage>
    with SingleTickerProviderStateMixin {
  AnimationController _controller;
  int colorindex = 0;
  final dbHelper = CreateNotes.instance;
  var pasedjson;
  bool showquote = false;
  List colors = [
    Color.fromRGBO(148, 0, 211, 1),
    Color.fromRGBO(138, 43, 226, 1),
    Colors.blue[800],
    Colors.red[900],
    Colors.teal
  ];

  _makeGetRequest() async {
    // make GET request

    String url = 'https://zenquotes.io/api/today';
    Response response = await get(url); // sample info available in response
    print(response.body);
    setState(() {
      pasedjson = json.decode(response.body);
      showquote = true;
    });
  }

  @override
  void initState() {
    getList().listen((event) {
      print(event);
    });
    _streamController = StreamController();
    _stream = _streamController.stream;
    _controller = AnimationController(
      vsync: this, // the SingleTickerProviderStateMixin
      duration:
          Duration(seconds: 1), // how long should the animation take to finish
    );
    _makeGetRequest();
    super.initState();
  }

  @override
  dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          centerTitle: true,
          backgroundColor: Colors.black,
          title: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(
                Icons.edit,
                color: Colors.white,
                size: 20,
              ),
              Text("Note",
                  style: GoogleFonts.montserratAlternates(
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                    fontSize: 20,
                  )),
              Text(
                "Share",
                style: GoogleFonts.montserratAlternates(
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                    fontSize: 20),
              ),
            ],
          ),
        ),
        floatingActionButton: FloatingActionButton(
          focusColor: Colors.white,
          child: AnimatedIcon(
            icon:
                AnimatedIcons.add_event, // one of the available animated icons
            progress: _controller, // this is our AnimationController
            color: Colors.white,
          ),
          onPressed: () {
            showDialog(
                context: context,
                builder: (_) {
                  return AlertBox();
                });
          },
          backgroundColor: colors[2],
          splashColor: Colors.blue,
          hoverColor: Colors.red,
        ),
        body: Container(
          color: Colors.black,
          child: StreamBuilder(
            stream: _stream,
            builder: (BuildContext ctx, AsyncSnapshot snapshot) {
              if (snapshot.data == null) {
                return Center(child: CircularProgressIndicator());
              }
              if (snapshot.data.length == 0) {
                _controller.repeat(reverse: true, period: Duration(seconds: 1));
                return Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(
                        Icons.sentiment_very_dissatisfied,
                        color: Colors.grey[900],
                        size: MediaQuery.of(context).size.width * 0.7,
                      ),
                      Text(
                        "Empty Locker",
                        style: GoogleFonts.roboto(
                            color: Colors.white, fontSize: 17),
                      ),
                      Text(
                        "Create Your first Locker",
                        style: GoogleFonts.roboto(
                            color: Colors.white, fontSize: 17),
                      )
                    ],
                  ),
                );
              } else {
                _controller.reset();
                return Container(
                  width: MediaQuery.of(context).size.width,
                  height: MediaQuery.of(context).size.height,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      showquote? Card(
                        color: Colors.black,
                        elevation: 1,
                        shadowColor: Colors.white,
                        child: Container(
                          padding: EdgeInsets.all(10),
                          child: Column(
                            children: [
                              Text("${pasedjson[0]['q']}",
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      color: Colors.white,
                                      fontSize: 16)),
                              Row(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  Text("-",
                                      style: TextStyle(
                                          color: Colors.red, fontSize: 16)),
                                  Text("${pasedjson[0]['a']}",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.red,
                                          fontSize: 16)),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ): Container(),
                      Expanded(
                        child: GridView.builder(
                            padding: EdgeInsets.all(20),
                            itemCount: snapshot.data.length,
                            gridDelegate:
                                new SliverGridDelegateWithFixedCrossAxisCount(
                                    crossAxisCount: 2),
                            itemBuilder: (BuildContext context, int index) {
                              bool checkval = true;
                              if (index > 4) {
                                colorindex = index % 5;
                                checkval = false;
                              }
                              return Container(
                                child: Stack(
                                  children: [
                                    Align(
                                        alignment: Alignment.topCenter,
                                        child: CircleAvatar(
                                          backgroundColor: Colors.white,
                                          radius: 30,
                                          child: Column(
                                            children: [
                                              Icon(
                                                Icons.lock,
                                                size: 25,
                                                color: checkval
                                                    ? colors[index]
                                                    : colors[colorindex],
                                              ),
                                            ],
                                          ),
                                        )),
                                    Padding(
                                      padding: const EdgeInsets.all(20.0),
                                      child: InkWell(
                                        splashColor: Colors.blue,
                                        onTap: () async {
                                          Navigator.push(
                                              context,
                                              MaterialPageRoute(
                                                builder: (context) => Locker(
                                                  lockername:
                                                      snapshot.data[index]
                                                          ['lockername'],
                                                  username: snapshot.data[index]
                                                      ['username'],
                                                  password: snapshot.data[index]
                                                      ['password'],
                                                  comments: snapshot.data[index]
                                                      ['comments'],
                                                  color: checkval
                                                      ? colors[index]
                                                      : colors[colorindex],
                                                ),
                                              ));
                                        },
                                        child: Card(
                                            shape: RoundedRectangleBorder(
                                                borderRadius:
                                                    BorderRadius.circular(10)),
                                            elevation: 2,
                                            shadowColor: checkval
                                                ? colors[index]
                                                : colors[colorindex],
                                            color: checkval
                                                ? colors[index]
                                                : colors[colorindex],
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  top: -10,
                                                  right: 20,
                                                  child: Icon(
                                                    Icons.vpn_key,
                                                    size: 150,
                                                    color: Colors.black
                                                        .withOpacity(0.8),
                                                  ),
                                                ),
                                                Center(
                                                  child: Text(
                                                    '${snapshot.data[index]['lockername']}',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                        color: Colors.white,
                                                        fontSize: 25,
                                                        fontWeight:
                                                            FontWeight.bold),
                                                    overflow:
                                                        TextOverflow.ellipsis,
                                                    softWrap: true,
                                                    maxLines: 3,
                                                  ),
                                                ),
                                              ],
                                            )),
                                      ),
                                    ),
                                  ],
                                ),
                              );
                            }),
                      ),
                    ],
                  ),
                );
              }
            },
          ),
        ));
  }
}

class AlertBox extends StatefulWidget {
  @override
  _AlertBoxState createState() => _AlertBoxState();
}

class _AlertBoxState extends State<AlertBox> {
  final _formKey = GlobalKey<FormState>();
  bool namerror = false,
      usererror = false,
      passerror = false,
      mandatory = false; // for locker name validation
  var warning, mandatwarning;
  final nametext = TextEditingController(),
      username = TextEditingController(),
      password = TextEditingController(),
      comments = TextEditingController();
  FocusNode _myfocus = FocusNode(),
      namefocus = FocusNode(),
      passfocus = FocusNode(),
      comfocus = FocusNode();
  bool visibility = false;
  bool touched = false;

  void changefocus() async {
    if (!_myfocus.hasFocus) {
      var check = await checklocker(nametext.text);
      if (check == null) {
        setState(() {
          namerror = false;
        });
      } else {
        if (!check.isEmpty) {
          setState(() {
            namerror = true;
            warning = "This Lockername already exist";
          });
        } else {
          setState(() {
            namerror = false;
          });
        }
      }
    }
  }

  Future checklocker(String lockername) async {
    //final ffr = await dbHelper.delete('gmail');
    try {
      final dbHelper = CreateNotes.instance;
      final result = await dbHelper.checkName(lockername);
      return result;
    } catch (e) {
      print(e);
    }
  }

  Future insertNotes(String namefield, String usernamefield,
      String passwordfield, String commentsfield) async {
    final dbHelper = CreateNotes.instance;

    Map<String, dynamic> row = {
      CreateNotes.columnName: namefield,
      CreateNotes.columnUsername: usernamefield,
      CreateNotes.password: passwordfield,
      CreateNotes.comments: commentsfield
    };
    final id = await dbHelper.insert(row);
    print('inserted row id: $id');
  }

  void _requestFocus(FocusNode name) {
    setState(() {
      touched = true;
      FocusScope.of(context).requestFocus(name);
    });
  }

  @override
  void initState() {
    super.initState();
    _myfocus.addListener(changefocus);
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Container(
        color: Colors.black.withOpacity(0),
        child: SingleChildScrollView(
          child: Center(
            child: Column(
              children: [
                Container(
                  width: MediaQuery.of(context).size.width,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(
                        Icons.lock,
                        color: Colors.red,
                      ),
                      new Text(
                        "Create new locker",
                        style: TextStyle(
                            decoration: TextDecoration.none,
                            fontSize: 17,
                            color: Colors.white),
                      ),
                    ],
                  ),
                ),
                AlertDialog(
                  buttonPadding: EdgeInsets.all(10),
                  contentPadding: EdgeInsets.fromLTRB(10, 10, 10, 0),
                  actions: [
                    RaisedButton(
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(5),
                      ),
                      elevation: 5,
                      child: Text(
                        'Create',
                        style: TextStyle(
                          color: Colors.white,
                        ),
                      ),
                      color: Colors.grey[900],
                      onPressed: () async {
                        if (_myfocus.hasFocus) {
                          var check = await checklocker(nametext.text);

                          if (check == null) {
                            setState(() {
                              namerror = false;
                            });
                          } else {
                            if (!check.isEmpty) {
                              setState(() {
                                namerror = true;
                                warning = "This Lockername already exist";
                              });
                            } else {
                              setState(() {
                                namerror = false;
                              });
                            }
                          }
                        }
                        if (_formKey.currentState.validate()) {
                          if (!namerror) {
                            //logic for db entry
                            try {
                              await insertNotes(nametext.text, username.text,
                                  password.text, comments.text);
                              final dbHelper = CreateNotes.instance;
                              final allRows = await dbHelper.queryAllRows();
                              _streamController.add(allRows);
                            } catch (e) {
                              print(e);
                            }

                            Navigator.of(context).pop();
                          }
                        } else {
                          print("false");
                        }
                      },
                    ),
                    RaisedButton(
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(5),
                      ),
                      elevation: 5,
                      child: Text(
                        'Cancel',
                        style: TextStyle(
                          color: Colors.white,
                        ),
                      ),
                      color: Colors.grey[900],
                      onPressed: () {
                        /* print(nametext.text);
                        print(password.text);
                        print(comments.text);
                        print(username.text); */

                        Navigator.of(context).pop();
                      },
                    ),
                  ],
                  backgroundColor: Colors.white,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(10),
                  ),
                  content: new Container(
                    padding: EdgeInsets.all(15),
                    child: SingleChildScrollView(
                      child: Form(
                        key: _formKey,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            TextFormField(
                              // ignore: missing_return
                              validator: (value) {
                                print(value);
                                if (value.isEmpty) {
                                  return 'required';
                                }
                              },
                              style: TextStyle(color: Colors.black),
                              cursorHeight: 20,
                              onTap: () {
                                _requestFocus(_myfocus);
                              },
                              cursorColor: Colors.black,
                              controller: nametext,
                              focusNode: _myfocus,
                              textAlign: TextAlign.center,
                              decoration: InputDecoration(
                                  labelText: "Name of locker*",
                                  errorText: namerror ? warning : null,
                                  labelStyle: TextStyle(
                                      color: touched
                                          ? Colors.black
                                          : Colors.grey[500]),
                                  enabledBorder: new OutlineInputBorder(
                                    borderRadius:
                                        new BorderRadius.circular(10.0),
                                    borderSide:
                                        BorderSide(color: Colors.grey[500]),
                                  ),
                                  focusedBorder: new OutlineInputBorder(
                                    borderRadius:
                                        new BorderRadius.circular(10.0),
                                    borderSide: BorderSide(
                                        color: Colors.blue, width: 2),
                                  ),
                                  focusColor: Colors.white,
                                  errorStyle: TextStyle(),
                                  hintText: "eg.Main Account",
                                  hintStyle: TextStyle(color: Colors.white)),
                            ),
                            SizedBox(
                              height: 10,
                            ),
                            TextFormField(
                              // ignore: missing_return
                              validator: (value) {
                                if (value.isEmpty) {
                                  return 'required*';
                                }
                              },
                              enableSuggestions: true,
                              style: TextStyle(color: Colors.black),
                              cursorHeight: 20,
                              onTap: () {
                                _requestFocus(namefocus);
                              },
                              cursorColor: Colors.black,
                              controller: username,
                              focusNode: namefocus,
                              textAlign: TextAlign.center,
                              decoration: InputDecoration(
                                  labelText: "Username/Email*",
                                  labelStyle: TextStyle(
                                      color: touched
                                          ? Colors.black
                                          : Colors.grey[500]),
                                  enabledBorder: new OutlineInputBorder(
                                    borderRadius:
                                        new BorderRadius.circular(10.0),
                                    borderSide:
                                        BorderSide(color: Colors.grey[500]),
                                  ),
                                  focusedBorder: new OutlineInputBorder(
                                    borderRadius:
                                        new BorderRadius.circular(10.0),
                                    borderSide: BorderSide(
                                        color: Colors.blue, width: 2),
                                  ),
                                  focusColor: Colors.white,
                                  errorStyle: TextStyle(),
                                  hintText: "eg.a@xmail.com",
                                  hintStyle: TextStyle(color: Colors.white)),
                            ),
                            SizedBox(
                              height: 10,
                            ),
                            TextFormField(
                              // ignore: missing_return
                              validator: (value) {
                                if (value.isEmpty) {
                                  return 'required*';
                                }
                              },
                              obscureText: !visibility,
                              style: TextStyle(color: Colors.black),
                              cursorHeight: 20,
                              onTap: () {
                                _requestFocus(passfocus);
                              },
                              cursorColor: Colors.black,
                              controller: password,
                              focusNode: passfocus,
                              textAlign: TextAlign.center,
                              decoration: InputDecoration(
                                  labelText: "Password*",
                                  errorText: passerror ? warning : null,
                                  suffixIcon: visibility
                                      ? InkWell(
                                          child: Icon(
                                            Icons.visibility_off,
                                            color: Colors.grey[500],
                                          ),
                                          onTap: () => setState(() {
                                                visibility = !visibility;
                                              }))
                                      : InkWell(
                                          child: Icon(Icons.visibility),
                                          onTap: () => setState(() {
                                                visibility = !visibility;
                                              })),
                                  enabledBorder: new OutlineInputBorder(
                                    borderRadius:
                                        new BorderRadius.circular(10.0),
                                    borderSide:
                                        BorderSide(color: Colors.grey[500]),
                                  ),
                                  focusedBorder: new OutlineInputBorder(
                                    borderRadius:
                                        new BorderRadius.circular(10.0),
                                    borderSide: BorderSide(
                                        color: Colors.blue, width: 2),
                                  ),
                                  focusColor: Colors.white,
                                  errorStyle: TextStyle(),
                                  hintStyle: TextStyle(color: Colors.white)),
                            ),
                            SizedBox(
                              height: 10,
                            ),
                            TextField(
                              style: TextStyle(color: Colors.black),
                              cursorHeight: 20,
                              onTap: () {
                                _requestFocus(comfocus);
                              },
                              cursorColor: Colors.black,
                              controller: comments,
                              focusNode: comfocus,
                              textAlign: TextAlign.center,
                              decoration: InputDecoration(
                                  labelText: "Extra Info",
                                  labelStyle: TextStyle(
                                      color: touched
                                          ? Colors.black
                                          : Colors.grey[500]),
                                  enabledBorder: new OutlineInputBorder(
                                    borderRadius:
                                        new BorderRadius.circular(10.0),
                                    borderSide:
                                        BorderSide(color: Colors.grey[500]),
                                  ),
                                  focusedBorder: new OutlineInputBorder(
                                    borderRadius:
                                        new BorderRadius.circular(10.0),
                                    borderSide: BorderSide(
                                        color: Colors.blue, width: 2),
                                  ),
                                  focusColor: Colors.white,
                                  errorStyle: TextStyle(),
                                  hintText: "eg.Main Account",
                                  hintStyle: TextStyle(color: Colors.white)),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
